version: '2'
services:
  picoshare:
    environment:
      - PORT=3001
    ports:
      - 80:3001
    volumes:
      - picoshare:/data
    container_name: picoshare
    image: mtlynch/picoshare:latest

volumes:
  picoshare:
  
networks:
  default:
    external:
      name: VLAN  
